//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FitPlan.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FitPlan.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add {0}.
        /// </summary>
        public static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close {0}.
        /// </summary>
        public static string Action_Close {
            get {
                return ResourceManager.GetString("Action_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create {0} Template.
        /// </summary>
        public static string Action_CreateTemplate {
            get {
                return ResourceManager.GetString("Action_CreateTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete {0}.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert {0}.
        /// </summary>
        public static string Action_Insert {
            get {
                return ResourceManager.GetString("Action_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock Date.
        /// </summary>
        public static string Action_LockDate {
            get {
                return ResourceManager.GetString("Action_LockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Action_Login {
            get {
                return ResourceManager.GetString("Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New {0}.
        /// </summary>
        public static string Action_New {
            get {
                return ResourceManager.GetString("Action_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string Action_SaveAs {
            get {
                return ResourceManager.GetString("Action_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Workout.
        /// </summary>
        public static string Action_ScheduleWorkout {
            get {
                return ResourceManager.GetString("Action_ScheduleWorkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show {0}.
        /// </summary>
        public static string Action_Show {
            get {
                return ResourceManager.GetString("Action_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock Date.
        /// </summary>
        public static string Action_UnlockDate {
            get {
                return ResourceManager.GetString("Action_UnlockDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Label_Activities {
            get {
                return ResourceManager.GetString("Label_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual {0}.
        /// </summary>
        public static string Label_Actual {
            get {
                return ResourceManager.GetString("Label_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}&apos;s Training Plan.
        /// </summary>
        public static string Label_AthletesTrainingPlan {
            get {
                return ResourceManager.GetString("Label_AthletesTrainingPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATL.
        /// </summary>
        public static string Label_ATL {
            get {
                return ResourceManager.GetString("Label_ATL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calc..
        /// </summary>
        public static string Label_Calculated {
            get {
                return ResourceManager.GetString("Label_Calculated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTL.
        /// </summary>
        public static string Label_CTL {
            get {
                return ResourceManager.GetString("Label_CTL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTL Target.
        /// </summary>
        public static string Label_CTLtarget {
            get {
                return ResourceManager.GetString("Label_CTLtarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cumulative.
        /// </summary>
        public static string Label_Cumulative {
            get {
                return ResourceManager.GetString("Label_Cumulative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Avg..
        /// </summary>
        public static string Label_DailyAvg {
            get {
                return ResourceManager.GetString("Label_DailyAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delta {0}.
        /// </summary>
        public static string Label_Delta {
            get {
                return ResourceManager.GetString("Label_Delta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Label_Details {
            get {
                return ResourceManager.GetString("Label_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Drag template to link).
        /// </summary>
        public static string Label_DragTemplate {
            get {
                return ResourceManager.GetString("Label_DragTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Label_Duration {
            get {
                return ResourceManager.GetString("Label_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Folders.
        /// </summary>
        public static string Label_EmptyFolders {
            get {
                return ResourceManager.GetString("Label_EmptyFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string Label_End {
            get {
                return ResourceManager.GetString("Label_End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate VDOT.
        /// </summary>
        public static string Label_EstimateVDOT {
            get {
                return ResourceManager.GetString("Label_EstimateVDOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fit Plan.
        /// </summary>
        public static string Label_FitPlan {
            get {
                return ResourceManager.GetString("Label_FitPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        public static string Label_Multiple {
            get {
                return ResourceManager.GetString("Label_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase.
        /// </summary>
        public static string Label_Phase {
            get {
                return ResourceManager.GetString("Label_Phase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phases.
        /// </summary>
        public static string Label_Phases {
            get {
                return ResourceManager.GetString("Label_Phases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Total.
        /// </summary>
        public static string Label_PhaseTotal {
            get {
                return ResourceManager.GetString("Label_PhaseTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Label_Plan {
            get {
                return ResourceManager.GetString("Label_Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Planning.
        /// </summary>
        public static string Label_Planning {
            get {
                return ResourceManager.GetString("Label_Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Overview.
        /// </summary>
        public static string Label_PlanOverview {
            get {
                return ResourceManager.GetString("Label_PlanOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string Label_Progress {
            get {
                return ResourceManager.GetString("Label_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramp.
        /// </summary>
        public static string Label_Ramp {
            get {
                return ResourceManager.GetString("Label_Ramp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        public static string Label_Repeat {
            get {
                return ResourceManager.GetString("Label_Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string Label_Summary {
            get {
                return ResourceManager.GetString("Label_Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tasks.
        /// </summary>
        public static string Label_Tasks {
            get {
                return ResourceManager.GetString("Label_Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Label_Template {
            get {
                return ResourceManager.GetString("Label_Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Load.
        /// </summary>
        public static string Label_TrainingLoad {
            get {
                return ResourceManager.GetString("Label_TrainingLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRIMP.
        /// </summary>
        public static string Label_Trimp {
            get {
                return ResourceManager.GetString("Label_Trimp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSB.
        /// </summary>
        public static string Label_TSB {
            get {
                return ResourceManager.GetString("Label_TSB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TSS.
        /// </summary>
        public static string Label_TSS {
            get {
                return ResourceManager.GetString("Label_TSS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Avg..
        /// </summary>
        public static string Label_WeeklyAvg {
            get {
                return ResourceManager.GetString("Label_WeeklyAvg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week View.
        /// </summary>
        public static string Label_WeekView {
            get {
                return ResourceManager.GetString("Label_WeekView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout.
        /// </summary>
        public static string Label_Workout {
            get {
                return ResourceManager.GetString("Label_Workout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workout Library.
        /// </summary>
        public static string Label_WorkoutLibrary {
            get {
                return ResourceManager.GetString("Label_WorkoutLibrary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This phase contains {0} workouts.  Move workouts to phase {1}?  If not, the workouts will be deleted..
        /// </summary>
        public static string Text_DeletePhaseWarning {
            get {
                return ResourceManager.GetString("Text_DeletePhaseWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This change will shorten a phase and delete {0} workout(s).  Delete the workouts and continue?.
        /// </summary>
        public static string Text_DeleteWorkouts {
            get {
                return ResourceManager.GetString("Text_DeleteWorkouts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upgrade to enable more than {0} workouts..
        /// </summary>
        public static string Text_EvalMessage {
            get {
                return ResourceManager.GetString("Text_EvalMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Fit Plan is a collection of Phases, and Phases contain Workouts.  Fit Plans can be saved to a file for later or shared with others..
        /// </summary>
        public static string Text_PlanHelp {
            get {
                return ResourceManager.GetString("Text_PlanHelp", resourceCulture);
            }
        }
    }
}
